envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GEMINI_API_KEY
        fromService:
          type: secret_file
          name: gemini_api_key
          key: GEMINI_API_KEY
      - key: SECRET_KEY
        generateValue: true
      - key: SECRET_REGISTRATION_KEY
        fromService:
          type: secret_file
          name: my_secrets
          key: SECRET_REGISTRATION_KEY
      - key: SECRET_STUDENT_KEY
        fromService:
          type: secret_file
          name: my_secrets
          key: SECRET_STUDENT_KEY
      - key: SECRET_TEACHER_KEY
        fromService:
          type: secret_file
          name: my_secrets
          key: SECRET_TEACHER_KEY
      - key: STRIPE_SECRET_KEY
        fromService:
          type: secret_file
          name: my_secrets
          key: STRIPE_SECRET_KEY
      - key: STRIPE_PUBLIC_KEY
        fromService:
          type: secret_file
          name: my_secrets
          key: STRIPE_PUBLIC_KEY
      - key: STRIPE_PRO_PRICE_ID
        fromService:
          type: secret_file
          name: my_secrets
          key: STRIPE_PRO_PRICE_ID
      - key: STRIPE_ULTRA_PRICE_ID
        fromService:
          type: secret_file
          name: my_secrets
          key: STRIPE_ULTRA_PRICE_ID
      - key: STRIPE_STUDENT_PRICE_ID
        fromService:
          type: secret_file
          name: my_secrets
          key: STRIPE_STUDENT_PRICE_ID
      - key: YOUR_DOMAIN
        fromService:
          type: secret_file
          name: my_secrets
          key: YOUR_DOMAIN
